Repository ACM-VIT/dolos, pull requests merged in 2020-10, with the labels that each got.

#9 Basic Code Structure
  .gitignore
  package-lock.json
  package.json
  src/api/TextResponses.js
  src/app.js
  src/routes/api.routes.js
Labels: code, enhancement

#16 added a database connection script
  package-lock.json
  package.json
  src/app.js
  src/database.js
Labels: hacktoberfest, ready-to-merge

#22 Adding Github Actions
  .github/workflows/node.js.yml
  README.md
Labels: hacktoberfest, ready-to-merge

#31 added forks and stars badges
  README.md
Labels: hacktoberfest, ready-to-merge

#46 Fix for CI
  package-lock.json
Labels: hacktoberfest, ready-to-merge

#35 Added .env.example + Added test script for server.
  .env.example
  src/app.js
  src/tests/app.test.js
  src/tests/sampleTest.test.js
Labels: hacktoberfest, ready-to-merge

#32 Add Last commit status and repo size
  README.md
  package-lock.json
Labels: hacktoberfest, ready-to-merge

#33 Add Eslint, Prettier, Husky
  .eslintrc.js
  package-lock.json
  package.json
  src/app.js
  src/database.js
  src/routes/api.routes.js
  src/tests/app.test.js
  src/tests/sampleTest.test.js
Labels: hacktoberfest, ready-to-merge

#51 load env configs for dbms connectivity
  .env.example
  src/database.js
Labels: hacktoberfest, ready-to-merge

#44 Added env variables for db connectivity
  src/database.js
Labels: hacktoberfest, ready-to-merge

#59 Integrate APIDocs
  apidoc.json
  package.json
  src/database.js
  src/routes/api.routes.js
Labels: hacktoberfest, ready-to-merge

#43 Readme improvements
  PULL_REQUEST_TEMPLATE.md
  README.md
  docs/PULL_REQUEST.md
  docs/SUBMITTING_PULL_REQUEST.md
Labels: hacktoberfest, ready-to-merge

#50 add .env.database for database and docker for development
  .dockerignore
  .env.example
  Dockerfile
  README.md
  docker-compose.yml
  package-lock.json
  src/database.js
Labels: hacktoberfest, ready-to-merge

#61 Fix CI Build , other minor fixes.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/node.js.yml
  README.md
  docs/PLAN.md
  package-lock.json
  package.json
  src/app.js
  src/database.js
  src/server.js
  src/tests/app.test.js
  src/tests/sampleTest.test.js
Labels: bug, hacktoberfest, ready-to-merge

#64 Fix #63 : Add database of dummy data
  migration/database.dump.sql
Labels: hacktoberfest, ready-to-merge

#66 Fix #41 : Implement Schema processor
  src/api/Parser.js
  src/api/workers/number.js
  src/api/workers/string.country.js
  src/api/workers/string.enum.js
  src/api/workers/string.firstName.js
  src/api/workers/string.lastName.js
  src/routes/api.routes.js
Labels: enhancement, hacktoberfest, ready-to-merge

#69 Added Logos in .png format
  Logo_png/Dolos_Logo_Dark.png
  Logo_png/Dolos_Logo_Light.png
  Logo_png/Dolos_Logo_Transparent_BlackLines.png
  Logo_png/Dolos_Logo_Transparent_WhiteLines.png
  README.md
Labels: hacktoberfest, hacktoberfest-merged
